### ISSUE TITLE
这很重要！你必须认真阅读这个issue

### ISSUE THREAD

**Issue by Qizhen-Yang** [lihansen12345/lihansen12345.github.io#1]
以下是来自newtab原作者的警告：

你已经违反了我的GPL v3.0开源许可证，并且在你已经发布的页面中你删除了我的版权信息，这是一个非常严肃的问题，你应该认真对待。你侵犯了我的版权（著作权），也违反了相关开源的许可证。

如果你仍然无视我的版权声明和许可证，我有权利向GitHub举报你。这可能导致更严重的后果，如删仓库，封号等。

我希望你能够认真对待这件事，如果你并没有，那么我就要考虑更多有关版权纠纷的处理方式了。

你应该立即删除和newtab相关的页面和文件，并使用fork的功能而不是直接复制。

感谢你的配合，如有疑问，邮箱联系： <alejandro_yang@yeah.net>，限时两周，两周后我将采取相关措施。

**Comment by lihansen12345** [comment]
在第13天删除了
